### ISSUE TITLE
那么能否支持动态评论获取呢？

### ISSUE THREAD

**Issue by sakurayun** [circle-hotaru/bilibili-comment2png#16]
希望支持动态评论获取，以及评论的回复获取（）

**Comment by circle-hotaru** [comment]
可以获取动态评论和评论的回复。但是和这个项目的功能不符，希望可以提供使用场景。
如果需要的话，你可以通过 https://github.com/SocialSisterYi/bilibili-API-collect 这个项目提供的接口获取
